const loginRoutes = require('./User/loginRoutes');
const roleRoutes = require('./Master/roleRoutes');
const languageRoutes = require('./Master/languageRoutes');
const otpTypeRoutes = require('./Master/otpTypeRoutes');
const userRoutes = require('./User/userRoutes');
const category = require('./Master/category.routes');
const subcategory = require('./Master/subcategory.routes');
const blog = require('./Master/blog.routes');
const transaction = require('./Master/transaction.routes');
const company = require('./Master/company.routes');
const designation = require('./Master/designation.routes');
const state = require('./Master/state.routes');
const city = require('./Master/city.routes');
const packageRoute = require('./Master/package.routes');
const reviews = require('./Master/reviews.routes');
const wallet = require('./Master/wallet.routes');
const notification = require('./Master/notification.routes');
const scheduleCall = require('./Master/schedule_call.routes');
const filter = require('./Master/filter.routes');
const packageSubscription = require('./Master/package_subscription.routes');
const adminSkillRoutes = require('./Admin/skill.routes');
const adminEarningRoutes = require('./Admin/earning.routes');
const adminBannerRoutes = require('./Admin/banner_management.routes');
const adminWithdrawMethodRoutes = require('./Admin/withdraw_method.routes');
const adminWithdrawRequestRoutes = require('./Admin/withdraw_request.routes');
const adminReasonSummaryRoutes = require('./Admin/reason_summary.routes');
const adminCallTypeRoutes = require('./Admin/call_type.routes');
const adminUserRoutes = require('./Admin/user.routes');
const adminNotificationShareRoutes = require('./Admin/notification_share.routes');
const adminGeneralSettingRoutes = require('./Admin/general.setting.routes');
const advisorRoutes = require('./Advisor/Advisor.routes');
const adminTicketsRoutes = require('./Admin/tickets.routes');
const adminTicketReplyRoutes = require('./Admin/ticket_Reply.routes');
const adminFaqRoutes = require('./Admin/faq.routes');
const adminFaqReplyRoutes = require('./Admin/faq_Reply.routes');
const adminDeleteAccountRoutes = require('./Admin/delete.account.routes');
const pageManagementRoutes = require('./Admin/page_management.routes');
const fileUploadRoutes = require('./Master/file_upload.routes');
const bank = require('./Advisor/Advisor_bankAccountDetails.routes');
const agoraRoutes = require('./agora.routes');
const paymentDetailsRoutes = require('./Master/payment_details.routes');
const adminPackageApprovalRoutes = require('./Admin/package_approval.routes');
const advisorPackageRoutes = require('./Master/advisor_package.routes');

function routes(app) {

    app.use('/api/bank', bank);
    app.use('/api', loginRoutes);
    app.use('/api/user', userRoutes);
    app.use('/api/roles', roleRoutes);
    app.use('/api/languages', languageRoutes);
    app.use('/api/otp-types', otpTypeRoutes);
    app.use('/api/category', category);
    app.use('/api/subcategory', subcategory);
    app.use('/api/blog', blog);
    app.use('/api/transaction', transaction);
    app.use('/api/company', company);
    app.use('/api/designation', designation);
    app.use('/api/state', state);
    app.use('/api/city', city);
    app.use('/api/package', packageRoute);
    app.use('/api/reviews', reviews);
    app.use('/api/wallet', wallet);
    app.use('/api/notification', notification);
    app.use('/api/schedule-call', scheduleCall);
    app.use('/api/filter', filter);
    app.use('/api/package-subscription', packageSubscription);
    app.use('/api/admin/skill', adminSkillRoutes);
    app.use('/api/admin/earning', adminEarningRoutes);
    app.use('/api/admin/banner', adminBannerRoutes);
    app.use('/api/admin/withdraw-method', adminWithdrawMethodRoutes);
    app.use('/api/admin/withdraw-request', adminWithdrawRequestRoutes);
    app.use('/api/admin/reason-summary', adminReasonSummaryRoutes);
    app.use('/api/admin/call-type', adminCallTypeRoutes);
    app.use('/api/admin/user', adminUserRoutes);
    app.use('/api/admin/notification-share', adminNotificationShareRoutes);
    app.use('/api/admin/general-setting', adminGeneralSettingRoutes);
    app.use('/api/admin/tickets', adminTicketsRoutes);
    app.use('/api/admin/ticket-reply', adminTicketReplyRoutes);
    app.use('/api/admin/faq', adminFaqRoutes);
    app.use('/api/admin/faq-reply', adminFaqReplyRoutes);
    app.use('/api/admin/delete-account', adminDeleteAccountRoutes);
    app.use('/api/advisor', advisorRoutes);
    app.use('/api/admin/page-management', pageManagementRoutes);
    app.use('/api/file-upload', fileUploadRoutes);
    app.use('/api/agora', agoraRoutes);
    app.use('/api/payment-details', paymentDetailsRoutes);
    app.use('/api/admin/package-approval', adminPackageApprovalRoutes);
    app.use('/api/advisor-package', advisorPackageRoutes);
}

module.exports = routes;